### ISSUE TITLE
null error from chat

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#1536]
This is happening on TF whenever someone chats:

```
[20:20:36] [Async Chat Thread - #0/ERROR]: [TotalFreedomMod] null
at me.totalfreedom.totalfreedommod.ChatManager.handleChatEvent(ChatManager.java:95) ~[TotalFreedomMod.jar:?]
at me.totalfreedom.totalfreedommod.ChatManager.onPlayerChatFormat(ChatManager.java:35) [TotalFreedomMod.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
at net.minecraft.server.v1_9_R1.PlayerConnection.chat(PlayerConnection.java:1264) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1202) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
at net.minecraft.server.v1_9_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
```

**Comment by Wild1145** [comment]
Thats strange... It doesnt like line 95 and there is no line 95, the last line is 94... How strange...

**Comment by JeromSar** [comment]
@ChargedCreeper Thanks for the report. The issue has been fixed.

@Wild1145 The repo is currently out of sync as I am ironing out the last bugs. :)

**Comment by Wild1145** [comment]
@JeromSar That would explain it...
