### ISSUE TITLE
Saconfig not erroring properly

### ISSUE THREAD

**Issue by Wild1145** [TotalFreedom/TotalFreedomMod#1545]
It looks like if you try to remove an admin entry that doesn't exist you get an NPE:

:saconfig remove KM_Eggsey
:[21:17:59 ERROR]: [TotalFreedomMod] Uncaught exception executing command: saconfig
:[21:17:59 ERROR]: [TotalFreedomMod] nulljava.lang.NullPointerException
:Command error: Unknown cause

**Comment by Wild1145** [comment]
Correction, it appears to be happening with every saconfig remove attempt:

> :saconfig remove KM_Eggsy
:[21:20:35 ERROR]: [TotalFreedomMod] Uncaught exception executing command: saconfig
:[21:20:35 ERROR]: [TotalFreedomMod] nulljava.lang.NullPointerException
	at net.pravian.aero.util.Ips.getIp(Ips.java:84)
	at me.totalfreedom.totalfreedommod.admin.AdminList.getAdmin(AdminList.java:171)
	at me.totalfreedom.totalfreedommod.command.Command_saconfig.run(Command_saconfig.java:271)
	at me.totalfreedom.totalfreedommod.command.FreedomCommand.runCommand(FreedomCommand.java:54)
	at me.totalfreedom.totalfreedommod.command.FreedomCommandExecutor.onCommand(FreedomCommandExecutor.java:63)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
	at me.totalfreedom.bukkittelnet.session.ClientSession$1.run(ClientSession.java:198)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
	at java.lang.Thread.run(Thread.java:745)
:Command error: Unknown cause

**Comment by JeromSar** [comment]
Fixed. Thanks for the report.
