### ISSUE TITLE
Task StackOverflowError

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#1563]
```
[00:43:34] [Server thread/WARN]: [TotalFreedomMod] Task #8916 for TotalFreedomMod v5.0 generated an exception
java.lang.StackOverflowError
at org.json.simple.JSONArray.toJSONString(JSONArray.java:79) ~[minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.json.simple.JSONArray.toJSONString(JSONArray.java:98) ~[minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.json.simple.JSONValue.toJSONString(JSONValue.java:199) ~[minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.json.simple.JSONArray.toJSONString(JSONArray.java:91) ~[minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.json.simple.JSONArray.toJSONString(JSONArray.java:98) ~[minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.json.simple.JSONValue.toJSONString(JSONValue.java:199) ~[minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.json.simple.JSONArray.toJSONString(JSONArray.java:91) ~[minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.json.simple.JSONArray.toJSONString(JSONArray.java:98) ~[minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.json.simple.JSONValue.toJSONString(JSONValue.java:199) ~[minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.json.simple.JSONArray.toJSONString(JSONArray.java:91) ~[minecraft_server.jar:git-Spigot-3104eb1-0705465]
```

**Comment by JeromSar** [comment]
Fixed. Thanks!

**Comment by ChargedCreeper** [comment]
@JeromSar I found another error. Not sure if it is related or not though:

```
[00:59:59] [Server thread/WARN]: [TotalFreedomMod] Task #2121 for TotalFreedomMod v5.0 generated an exception
java.lang.NullPointerException
at me.totalfreedom.totalfreedommod.player.FPlayer$1.run(FPlayer.java:288) ~[?:?]
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
```

**Comment by JeromSar** [comment]
@ChargedCreeper Nope, that is not related. Issue created: #1568
