### ISSUE TITLE
NPE in FPlayer

### ISSUE THREAD

**Issue by JeromSar** [TotalFreedom/TotalFreedomMod#1568]
From https://github.com/TotalFreedom/TotalFreedomMod/issues/1563#issuecomment-197093029

```
[00:59:59] [Server thread/WARN]: [TotalFreedomMod] Task #2121 for TotalFreedomMod v5.0 generated an exception
java.lang.NullPointerException
at me.totalfreedom.totalfreedommod.player.FPlayer$1.run(FPlayer.java:288) ~[?:?]
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
```

**Comment by Adaptified** [comment]
As me and @JeromSar established on skype,

This is thrown during the 5m timer unmute runnabletask. Should be fixed soon!

**Comment by JeromSar** [comment]
@Adaptified With all due respect, we didn't establish anything. The bug was already fixed when you told me.

**Comment by Adaptified** [comment]
@JeromSar Maybe you read that wrong, established as in I confirmed with you that this was the problem.
