### ISSUE TITLE
IllegalPluginAccessException

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#1605]
This happened during a reload caused by turning off onlinemode.

```
[01:02:58] [Craft Scheduler Thread - 3/ERROR]: [TotalFreedomMod] null
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:400) ~[minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:123) ~[minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:106) ~[minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:89) ~[minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.bukkit.scheduler.BukkitRunnable.runTask(BukkitRunnable.java:32) ~[minecraft_server.jar:git-Spigot-3104eb1-0705465]
at me.totalfreedom.totalfreedommod.command.Command_health$1.run(Command_health.java:48) [TotalFreedomMod.jar:?]
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [minecraft_server.jar:git-Spigot-3104eb1-0705465]
```

**Comment by DUFCLiam** [comment]
NOTE: It was a failure when it attempted a task and it was disabled

**Comment by JeromSar** [comment]
Thanks for the report @ChargedCreeper

**Comment by JeromSar** [comment]
Fixed in the latest update.
