### ISSUE TITLE
PotionSplashEvent Error (non-player throws a potion)

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#1622]
Looks to me like when a witch mob throws a potion... this happens. Should be a pretty easy fix.

```
[02:38:51] [Server thread/ERROR]: Could not pass event PotionSplashEvent to TotalFreedomMod v5.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[minecraft_server.jar:git-Spigot-944aa20-420b983]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-944aa20-420b983]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPotionSplashEvent(CraftEventFactory.java:344) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at net.minecraft.server.v1_9_R1.EntityPotion.a(EntityPotion.java:144) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at net.minecraft.server.v1_9_R1.EntityProjectile.m(EntityProjectile.java:164) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1612) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at net.minecraft.server.v1_9_R1.World.g(World.java:1587) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1421) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:629) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_9_R1.entity.CraftWitch cannot be cast to org.bukkit.entity.Player
```

**Comment by JeromSar** [comment]
@ChargedCreeper Thanks for the report.

**Comment by Adaptified** [comment]
Define the thrower as an entity instead of a Player.

**Comment by JeromSar** [comment]
@Adaptified I'm confused, what?

**Comment by DUFCLiam** [comment]
@JeromSar When you are trying to pass onPotionSplashEvent it has been defined as player rather than entity.

**Comment by JeromSar** [comment]
Fixed in latest build.
