### ISSUE TITLE
Mob Spawner Crash Command

### ISSUE THREAD

**Issue by WilliePlaysMC** [TotalFreedom/TotalFreedomMod#1627]
:[21:42:48 INFO]: DarkXFiles issued server command: /spawnmob pig,minecart 10
:[21:42:48 ERROR]: Encountered an unexpected exceptionnet.minecraft.server.v1_9_R1.ReportedException: Ticking entity
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:803)
at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Circular entity riding! EntityMinecartRideable['entity.MinecartRideable.name'/114, l='miwo-land', x=310.49, y=100.67, z=-412.50] EntityPig['Pig'/113, l='miwo-land', x=310.46, y=100.00, z=-412.50]
at com.google.common.base.Preconditions.checkState(Preconditions.java:200)
at net.minecraft.server.v1_9_R1.Entity.o(Entity.java:1672)
at net.minecraft.server.v1_9_R1.Entity.a(Entity.java:1641)
at net.minecraft.server.v1_9_R1.EntityInsentient.a(EntityInsentient.java:1079)
at net.minecraft.server.v1_9_R1.Entity.startRiding(Entity.java:1629)
at net.minecraft.server.v1_9_R1.EntityMinecartAbstract.collide(EntityMinecartAbstract.java:684)
at net.minecraft.server.v1_9_R1.EntityLiving.C(EntityLiving.java:2006)
at net.minecraft.server.v1_9_R1.EntityLiving.cn(EntityLiving.java:1999)
at net.minecraft.server.v1_9_R1.EntityLiving.n(EntityLiving.java:1951)
at net.minecraft.server.v1_9_R1.EntityInsentient.n(EntityInsentient.java:480)
at net.minecraft.server.v1_9_R1.EntityAgeable.n(EntityAgeable.java:146)
at net.minecraft.server.v1_9_R1.EntityAnimal.n(EntityAnimal.java:23)
at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1775)
at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:243)
at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1612)
at net.minecraft.server.v1_9_R1.World.g(World.java:1587)
at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1421)
at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:629)
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792)
... 4 more

**:[21:42:48 ERROR]: Cause of unexpected exception wasjava.lang.IllegalStateException: Circular entity riding! EntityMinecartRideable['entity.MinecartRideable.name'/114, l='miwo-land', x=310.49, y=100.67, z=-412.50] EntityPig['Pig'/113, l='miwo-land', x=310.46, y=100.00, z=-412.50]**
at com.google.common.base.Preconditions.checkState(Preconditions.java:200)
at net.minecraft.server.v1_9_R1.Entity.o(Entity.java:1672)
at net.minecraft.server.v1_9_R1.Entity.a(Entity.java:1641)
at net.minecraft.server.v1_9_R1.EntityInsentient.a(EntityInsentient.java:1079)
at net.minecraft.server.v1_9_R1.Entity.startRiding(Entity.java:1629)
at net.minecraft.server.v1_9_R1.EntityMinecartAbstract.collide(EntityMinecartAbstract.java:684)
at net.minecraft.server.v1_9_R1.EntityLiving.C(EntityLiving.java:2006)
at net.minecraft.server.v1_9_R1.EntityLiving.cn(EntityLiving.java:1999)
at net.minecraft.server.v1_9_R1.EntityLiving.n(EntityLiving.java:1951)
at net.minecraft.server.v1_9_R1.EntityInsentient.n(EntityInsentient.java:480)
at net.minecraft.server.v1_9_R1.EntityAgeable.n(EntityAgeable.java:146)
at net.minecraft.server.v1_9_R1.EntityAnimal.n(EntityAnimal.java:23)
at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1775)
at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:243)
at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1612)
at net.minecraft.server.v1_9_R1.World.g(World.java:1587)
at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1421)
at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:629)
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792)
at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
at java.lang.Thread.run(Thread.java:745)

:[21:42:48 ERROR]: This crash report has been saved to: /.rw/games/minecraft/beta/299668/./crash-reports/crash-2016-04-22_21.42.48-server.txt
:[21:42:48 INFO]: Stopping server

Read more: http://totalfreedom.boards.net/thread/38812/server-crasher#ixzz46bmRQyJc

For some odd reason the server crashes whenever someone spawns that mob spawner.
Steven says, "As explained in a different thread: the minecart is on top of the pig, but because mobs want to get in minecarts, the pig is trying to be at the top and bottom of the stack at the same time, causing a circle or infinite loop."

**Comment by Wild1145** [comment]
Confirmed, it just happened to the CJF Legacy server.

**Comment by AssassinDude** [comment]
lol i wouldnt be posting commands like this people are allready doing this as of now the server is off

**Comment by Wild1145** [comment]
@AssassinDude If we dont know the command, how can we block it / patch it?

**Comment by JeromSar** [comment]
Fixed in latest build.
