### ISSUE TITLE
Stfu -s

### ISSUE THREAD

**Issue by marcocorriero** [TotalFreedom/TotalFreedomMod#1750]
Stfu -s is broken, 

Error

[00:44:17] [Server thread/INFO]: marcocorriero11 issued server command: /stfu -s
[00:44:17] [Server thread/ERROR]: [TotalFreedomMod] Uncaught exception executing command: stfu
[00:44:17] [Server thread/ERROR]: [TotalFreedomMod] null
java.lang.ArrayIndexOutOfBoundsException: 0
at me.totalfreedom.totalfreedommod.command.Command_stfu.run(Command_stfu.java:92) ~[TotalFreedomMod.jar:?]
at me.totalfreedom.totalfreedommod.command.FreedomCommand.runCommand(FreedomCommand.java:53) [TotalFreedomMod.jar:?]
at me.totalfreedom.totalfreedommod.command.FreedomCommandExecutor.onCommand(FreedomCommandExecutor.java:80) [TotalFreedomMod.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-944aa20-420b983]
at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-944aa20-420b983]

**Comment by AvalancheYT** [comment]
You did it wrong, it's ```/stfu -s <player>``` not ```/stfu -s```
