### ISSUE TITLE
NPE With Announcer

### ISSUE THREAD

**Issue by PacksGamingHD** [TotalFreedom/TotalFreedomMod#1806]
[TotalFreedomMod] Unhandled exception whilst starting service 'Announcer'!>
[22:46:38 ERROR]: [TotalFreedomMod] java.lang.NullPointerException	at me.totalfreedom.totalfreedommod.Announcer.onStart(Announcer.java:37)	at net.pravian.aero.component.service.AbstractService.start(AbstractService.java:45)	at net.pravian.aero.component.service.ServiceManager.onStart(ServiceManager.java:21)	
at net.pravian.aero.component.service.AbstractService.start(AbstractService.java:45)	at me.totalfreedom.totalfreedommod.TotalFreedomMod.enable(TotalFreedomMod.java:198)	at net.pravian.aero.plugin.AeroPlugin.onEnable(AeroPlugin.java:81)	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362)	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322)	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)	at java.lang.Thread.run(Thread.java:745)

Edit: The reason is because there were no announcements

Edit 2: Even after adding announcements I still get the error

**Comment by Wild1145** [comment]
Try stopping the server, adding announcements, saving the file, closing the file and starting the server. TFM sometimes has some funnys with the config being edited on the fly if I remember.

**Comment by PacksGamingHD** [comment]
Regenerating the config file fixed the issue

Still a pain though

**Comment by JeromSar** [comment]
Still, there should be safeguards against these types of errors. Will look into. :)

**Comment by PacksGamingHD** [comment]
Yeah. I actually tried to make one but it didn't work.

I tried doing something like if (ConfigEntry.ANNOUNCEMENT_MESSAGES == null) {
then do code
}

**Comment by JeromSar** [comment]
@PacksGamingHD Did you edit the project's internal config.yml file?

**Comment by Telesphoreo** [comment]
If I recall I think I actually did

**Comment by JeromSar** [comment]
If you removed the "announcements" section, that might be the cause of this bug.

**Comment by Telesphoreo** [comment]
Yeah - The way it was that the owner of the server removed the announcements section :P
