### ISSUE TITLE
Could not load 'plugins/TotalFreedomMod.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by adriencyr** [TotalFreedom/TotalFreedomMod#1854]
So, I had to reinstall TFM because of my plugins being deleted, I installed Aero along with it and it comes up with this:
[18:19:58 ERROR]: Could not load 'plugins/TotalFreedomMod.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: WorldEdit
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:297) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
[18:19:58 INFO]: Set PluginClassLoader as parallel capable
[18:19:58 INFO]: [Aero] Loading Aero v2.0
[18:19:58 INFO]: [Aero] Enabling Aero v2.0
[18:19:58 INFO]: [Aero] Aero v2.0.249 by Prozza initialized
I could post the whole log if you guys want. Any help is appreciated :)

**Comment by mandar-ghade** [comment]
You probably did not add the TF WorldEdit, which I believe is the problem.

**Comment by mayokek** [comment]
`org.bukkit.plugin.UnknownDependencyException: WorldEdit` - This is your problem... You'll need to add TF-WorldEdit.6.1.(1 or 2).jar

**Comment by AandvarkOnGithub** [comment]
Could I please be linked to WorldEdit.6.1.jar?

**Comment by adriencyr** [comment]
Alright, I put WorldEdit on my server and I got these 3 errors:
[02:41:42 ERROR]: [TotalFreedomMod] Plugin TotalFreedomMod v5.0 has failed to register events for class me.totalfreedom.totalfreedommod.bridge.BukkitTelnetBridge because me/totalfreedom/bukkittelnet/api/TelnetPreLoginEvent does not exist.
[02:41:42 ERROR]: [TotalFreedomMod] Plugin TotalFreedomMod v5.0 has failed to register events for class me.totalfreedom.totalfreedommod.bridge.EssentialsBridge because com/earth2me/essentials/Essentials does not exist.
[02:41:42 ERROR]: [TotalFreedomMod] Plugin TotalFreedomMod v5.0 has failed to register events for class me.totalfreedom.totalfreedommod.bridge.WorldEditListener because me/totalfreedom/worldedit/LimitChangedEvent does not exist.

**Comment by adriencyr** [comment]
TFM works but I'd like to fix those 3 errors.

**Comment by mayokek** [comment]
You would need to add TF Essentials, TF WorldEdit and BukkitTelnet to the server.

**Comment by JeromSar** [comment]
Those are actually errors that can be ignored. They mean that BukkitTelnet, Essentials and TF's version of WorldEdit aren't available. TFM attempts to hook into those plugins, but it isn't required.
