### ISSUE TITLE
/mp44 does not work

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1877]
When someone enabled /mp44 draw, it does not work and spams this error:

[00:06:56 WARN]: [TotalFreedomMod] Task #1032 for TotalFreedomMod v5.0 generated an exception
java.lang.NullPointerException
        at me.totalfreedom.totalfreedommod.player.FPlayer$ArrowShooter.run(FPlayer.java:432) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by foxcqrn** [comment]
What even is /mp44 lol

**Comment by DUFCLiam** [comment]
`Modern weaponry, FTW. Use 'draw' to start firing, 'sling' to stop firing.`

**Comment by adroition** [comment]
@DUFCLiam When I use /mp44 draw and use the gunpowder, it does not fire and gives errors.

**Comment by DUFCLiam** [comment]
@adroition, Alright.
