### ISSUE TITLE
Unable to load TotalFreedomMod plugin

### ISSUE THREAD

**Issue by jclgc** [TotalFreedom/TotalFreedomMod#1992]
Whenever starting up my server it gives me this output:

`[21:27:34 ERROR]: Could not load 'plugins/TotalFreedomMod.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/pravian/aero/plugin/AeroPlugin
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot.jar:git-Spigot-de459a2-51263e9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NoClassDefFoundError: net/pravian/aero/plugin/AeroPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_72]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_72]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_72]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_72]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_72]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_72]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_72]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_72]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_72]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.pravian.aero.plugin.AeroPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_72]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_72]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_72]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_72]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_72]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_72]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_72]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_72]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_72]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	... 6 more`

The plugins that dow work are Aero and WorldEdit. You can find the whole startup log at https://pastebin.com/TL2tk5gB

**Comment by mayokek** [comment]
Use the latest [Aero plugin](https://github.com/TotalFreedom/TotalFreedomMod/releases/download/v5.0-mc1.10/Aero-2.0.jar).

**Comment by JeromSar** [comment]
@mayokek Is right, make sure you have the correct dependencies. :)
