### ISSUE TITLE
Cant use colorful MOTD

### ISSUE THREAD

**Issue by jclgc** [TotalFreedom/TotalFreedomMod#1997]
**Whenever using Colorful motd my console gets this error whenever someone refreshes their server list with my server in it:**

`[19:01:39 ERROR]: Could not pass event InternalServerListPingEvent to TotalFreedomMod v5.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-625bc00-41a7d14]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-625bc00-41a7d14]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-625bc00-41a7d14]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) ~[spigot.jar:git-Spigot-625bc00-41a7d14]
	at protocolsupport.protocol.packet.handler.AbstractStatusListener.lambda$handleStatusRequest$1(AbstractStatusListener.java:70) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_10_R1/CraftServer
	at me.totalfreedom.totalfreedommod.ServerInterface.getServer(ServerInterface.java:89) ~[?:?]
	at me.totalfreedom.totalfreedommod.ServerInterface.getVersion(ServerInterface.java:84) ~[?:?]
	at me.totalfreedom.totalfreedommod.ServerPing.onServerPing(ServerPing.java:58) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-625bc00-41a7d14]
	... 7 more
`

My settings are as following: 

  # You should change this to your server's name
  name: Justin’s Freedom

  # The address your server is located at. Please do not include the port.
  address: opjustin.ddns.net

  # Shown at the server list
  motd: Justins Freedom &8- Minecraft %mcversion%

  # Every word in the MOTD will be a different color unless prefixed by a color code
  colorful_motd: true

**Comment by ItzLevvie** [comment]
What version of Spigot are you using?

**Comment by Wild1145** [comment]
^ Yup, that'll do it.

**Comment by jclgc** [comment]
@ItzLevvie How do i compile from the `tfm5.1-mc1.11` branch? I've tried but i don't understand. I also tried editing the plugin (eg using Eclipse) but that doesn't work.

**Comment by Wild1145** [comment]
Thanks for contributing. I am closing this issue for inactivity. Should you have anything further to add in the future please either re-open the issue yourself or tag a member of staff and we will re-open the issue for further discussion.
