### ISSUE TITLE
TFM Error

### ISSUE THREAD

**Issue by Daisyuki** [TotalFreedom/TotalFreedomMod#1998]
I get an error about TFM whenever I load up my server and I dont know what to do.
And when I do /plugins it dont show up
-------------------------------------------------------------------------------------------------------------------
Loading libraries, please wait...
[16:29:13 INFO]: Starting minecraft server version 1.10.2
[16:29:14 INFO]: Loading properties
[16:29:14 INFO]: Default game type: SURVIVAL
[16:29:14 INFO]: This server is running CraftBukkit version git-Spigot-de459a2-51263e9 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
[16:29:14 INFO]: Debug logging is disabled
[16:29:14 INFO]: Server Ping Player Sample Count: 12
[16:29:14 INFO]: Using 4 threads for Netty based IO
[16:29:14 INFO]: Generating keypair
[16:29:15 INFO]: Starting Minecraft server on 192.168.0.14:9193
[16:29:15 INFO]: Using default channel type
[16:29:17 INFO]: Set PluginClassLoader as parallel capable
**[16:29:17 ERROR]: Could not load 'plugins\TotalFreedomMod.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/pravian/aero/plugin/AeroPlugin
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot.jar:git-Spigot-de459a2-51263e9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: net/pravian/aero/plugin/AeroPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_121]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_121]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_121]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: net.pravian.aero.plugin.AeroPlugin
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_121]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_121]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_121]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        ... 6 more**
[16:29:17 INFO]: [WorldEdit] Loading WorldEdit v6.0.2-TF;no_git_id
[16:29:17 INFO]: [BukkitTelnet] Loading BukkitTelnet v4.4
[16:29:17 INFO]: [Essentials] Loading Essentials vTeamCity
[16:29:17 INFO]: [EssentialsSpawn] Loading EssentialsSpawn vTeamCity
[16:29:17 INFO]: [Aero] Loading Aero v1.3
[16:29:17 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[16:29:17 INFO]: Preparing level "world"
[16:29:17 INFO]: -------- World Settings For [world] --------
[16:29:17 INFO]: Experience Merge Radius: 3.0
[16:29:17 INFO]: Item Despawn Rate: 6000
[16:29:17 INFO]: Item Merge Radius: 2.5
[16:29:17 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[16:29:17 INFO]: Arrow Despawn Rate: 1200
[16:29:17 INFO]: View Distance: 10
[16:29:17 INFO]: Zombie Aggressive Towards Villager: true
[16:29:17 INFO]: Nerfing mobs spawned from spawners: false
[16:29:17 INFO]: Cactus Growth Modifier: 100%
[16:29:17 INFO]: Cane Growth Modifier: 100%
[16:29:17 INFO]: Melon Growth Modifier: 100%
[16:29:17 INFO]: Mushroom Growth Modifier: 100%
[16:29:17 INFO]: Pumpkin Growth Modifier: 100%
[16:29:17 INFO]: Sapling Growth Modifier: 100%
[16:29:17 INFO]: Wheat Growth Modifier: 100%
[16:29:17 INFO]: NetherWart Growth Modifier: 100%
[16:29:17 INFO]: Vine Growth Modifier: 100%
[16:29:17 INFO]: Cocoa Growth Modifier: 100%
[16:29:17 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[16:29:17 INFO]: Mob Spawn Range: 4
[16:29:17 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[16:29:17 INFO]: Random Lighting Updates: false
[16:29:17 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[16:29:17 INFO]: Structure Info Saving: true
[16:29:17 INFO]: Max TNT Explosions: 100
[16:29:17 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[16:29:17 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[16:29:17 INFO]: Max Entity Collisions: 8
[16:29:17 INFO]: -------- World Settings For [world_nether] --------
[16:29:17 INFO]: Experience Merge Radius: 3.0
[16:29:17 INFO]: Item Despawn Rate: 6000
[16:29:17 INFO]: Item Merge Radius: 2.5
[16:29:17 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[16:29:17 INFO]: Arrow Despawn Rate: 1200
[16:29:17 INFO]: View Distance: 10
[16:29:17 INFO]: Zombie Aggressive Towards Villager: true
[16:29:17 INFO]: Nerfing mobs spawned from spawners: false
[16:29:17 INFO]: Cactus Growth Modifier: 100%
[16:29:17 INFO]: Cane Growth Modifier: 100%
[16:29:17 INFO]: Melon Growth Modifier: 100%
[16:29:17 INFO]: Mushroom Growth Modifier: 100%
[16:29:17 INFO]: Pumpkin Growth Modifier: 100%
[16:29:17 INFO]: Sapling Growth Modifier: 100%
[16:29:17 INFO]: Wheat Growth Modifier: 100%
[16:29:17 INFO]: NetherWart Growth Modifier: 100%
[16:29:17 INFO]: Vine Growth Modifier: 100%
[16:29:17 INFO]: Cocoa Growth Modifier: 100%
[16:29:17 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[16:29:17 INFO]: Mob Spawn Range: 4
[16:29:17 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[16:29:17 INFO]: Random Lighting Updates: false
[16:29:17 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[16:29:17 INFO]: Structure Info Saving: true
[16:29:17 INFO]: Max TNT Explosions: 100
[16:29:17 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[16:29:17 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[16:29:17 INFO]: Max Entity Collisions: 8
[16:29:18 INFO]: -------- World Settings For [world_the_end] --------
[16:29:18 INFO]: Experience Merge Radius: 3.0
[16:29:18 INFO]: Item Despawn Rate: 6000
[16:29:18 INFO]: Item Merge Radius: 2.5
[16:29:18 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[16:29:18 INFO]: Arrow Despawn Rate: 1200
[16:29:18 INFO]: View Distance: 10
[16:29:18 INFO]: Zombie Aggressive Towards Villager: true
[16:29:18 INFO]: Nerfing mobs spawned from spawners: false
[16:29:18 INFO]: Cactus Growth Modifier: 100%
[16:29:18 INFO]: Cane Growth Modifier: 100%
[16:29:18 INFO]: Melon Growth Modifier: 100%
[16:29:18 INFO]: Mushroom Growth Modifier: 100%
[16:29:18 INFO]: Pumpkin Growth Modifier: 100%
[16:29:18 INFO]: Sapling Growth Modifier: 100%
[16:29:18 INFO]: Wheat Growth Modifier: 100%
[16:29:18 INFO]: NetherWart Growth Modifier: 100%
[16:29:18 INFO]: Vine Growth Modifier: 100%
[16:29:18 INFO]: Cocoa Growth Modifier: 100%
[16:29:18 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[16:29:18 INFO]: Mob Spawn Range: 4
[16:29:18 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[16:29:18 INFO]: Random Lighting Updates: false
[16:29:18 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[16:29:18 INFO]: Structure Info Saving: true
[16:29:18 INFO]: Max TNT Explosions: 100
[16:29:18 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[16:29:18 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[16:29:18 INFO]: Max Entity Collisions: 8
[16:29:18 INFO]: Preparing start region for level 0 (Seed: -4018960102733653980)
[16:29:19 INFO]: Preparing spawn area: 0%
[16:29:20 INFO]: Preparing spawn area: 16%
[16:29:21 INFO]: Preparing spawn area: 38%
[16:29:22 INFO]: Preparing spawn area: 56%
[16:29:23 INFO]: Preparing spawn area: 75%
[16:29:24 INFO]: Preparing spawn area: 93%
[16:29:24 INFO]: Preparing start region for level 1 (Seed: -4018960102733653980)
[16:29:25 INFO]: Preparing spawn area: 18%
[16:29:26 INFO]: Preparing spawn area: 41%
[16:29:27 INFO]: Preparing spawn area: 60%
[16:29:28 INFO]: Preparing spawn area: 83%
[16:29:29 INFO]: Preparing start region for level 2 (Seed: -4018960102733653980)
[16:29:30 INFO]: [WorldEdit] Enabling WorldEdit v6.0.2-TF;no_git_id
[16:29:31 INFO]: WEPIF: Using the Bukkit Permissions API.
[16:29:31 WARN]: [WorldEdit]
**********************************************
** This WorldEdit version does not fully support your version of Bukkit.
**
** When working with blocks or undoing, chests will be empty, signs
** will be blank, and so on. There will be no support for entity
** and biome-related functions.
**
** Please see http://wiki.sk89q.com/wiki/WorldEdit/Bukkit_adapters
**********************************************

[16:29:31 INFO]: [BukkitTelnet] Enabling BukkitTelnet v4.4
[16:29:31 INFO]: [BukkitTelnet] Server started on 127.0.0.1:8765
[16:29:31 INFO]: [BukkitTelnet] BukkitTelnet v4.4 enabled
[16:29:31 INFO]: [Essentials] Enabling Essentials vTeamCity
[16:29:31 INFO]: Bukkit version format changed. Version not checked.
[16:29:31 INFO]: git-Spigot-de459a2-51263e9 (MC: 1.10.2)
[16:29:31 INFO]: 1.10.2-R0.1-SNAPSHOT
[16:29:31 INFO]: [Essentials] Starting Essentials ban format conversion
[16:29:31 INFO]: [Essentials] Found 1 files to convert...
[16:29:31 INFO]: [Essentials] Converted 0/1
[16:29:31 INFO]: [Essentials] Ban format update complete.
[16:29:31 INFO]: Using locale en_US
[16:29:31 INFO]: Using locale en_US
[16:29:32 INFO]: Essentials: Using config file enhanced permissions.
[16:29:32 INFO]: Permissions listed in as player-commands will be given to all users.
[16:29:32 INFO]: [EssentialsSpawn] Enabling EssentialsSpawn vTeamCity
[16:29:32 INFO]: [Aero] Enabling Aero v1.3
[16:29:32 INFO]: [Aero] The Config.yml File was successfully loaded.
[16:29:32 INFO]: [Aero] Aero v1.3 was enabled.
[16:29:32 INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:29:32 INFO]: Done (14.885s)! For help, type "help" or "?"
fixed.
all you have to do is get aero afgain

**Comment by mayokek** [comment]
You will need Aero plugin to be able to use TFM.

**Comment by jclgc** [comment]
I have this error too and i do have the Aero plugin just like @Daisyuki as you can see

> [16:29:32 INFO]: [Aero] Enabling Aero v1.3
> [16:29:32 INFO]: [Aero] The Config.yml File was successfully loaded.
> [16:29:32 INFO]: [Aero] Aero v1.3 was enabled.

**Comment by Wild1145** [comment]
You will need to make sure the Aero version and TFM and Spigot versions all match up

**Comment by Daisyuki** [comment]
I'm pretty sure that they all are matching because I downloaded them from the same page (TFM & Aero)

**Comment by ghost** [comment]
Have you renamed or done anything to the code of aero?

**Comment by Telesphoreo** [comment]
The latest version of Aero is not 1.3
23:53:50 INFO]: [Aero] Enabling Aero v2.0
[23:53:50 INFO]: [Aero] Aero v2.0.249 by Prozza initialized
is the mesasge you should get when the server starts up.
Go to the release page and download Aero from Electrum (MC 1.10)

**Comment by Wild1145** [comment]
Thanks for contributing. I am closing this issue for inactivity. Should you have anything further to add in the future please either re-open the issue yourself or tag a member of staff and we will re-open the issue for further discussion.
