### ISSUE TITLE
Cannot use worldedit

### ISSUE THREAD

**Issue by mgflames** [TotalFreedom/TotalFreedomMod#2086]
Hi there,

when I try to use TF-Worldedit and use //set, I get this error:

`22.07 17:19:46 [Server] ERROR [WorldEdit] An unexpected error while handling a WorldEdit command
22.07 17:19:46 [Server] INFO java.lang.NoSuchMethodError: com.google.common.base.Objects.firstNonNull(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
22.07 17:19:46 [Server] INFO at com.sk89q.worldedit.function.factory.Apply.createFromContext(Apply.java:51) ~[worldedit-bukkit-6.1.7-SNAPSHOT-dist.jar:?]
22.07 17:19:46 [Server] INFO at com.sk89q.worldedit.function.factory.Apply.createFromContext(Apply.java:33) ~[worldedit-bukkit-6.1.7-SNAPSHOT-dist.jar:?]
22.07 17:19:46 [Server] INFO at com.sk89q.worldedit.command.composition.SelectionCommand.call(SelectionCommand.java:83) ~[worldedit-bukkit-6.1.7-SNAPSHOT-dist.jar:?]
22.07 17:19:46 [Server] INFO at com.sk89q.worldedit.command.composition.SelectionCommand.call(SelectionCommand.java:46) ~[worldedit-bukkit-6.1.7-SNAPSHOT-dist.jar:?]
22.07 17:19:46 [Server] INFO at com.sk89q.worldedit.util.command.composition.LegacyCommandAdapter.call(LegacyCommandAdapter.java:52) ~[worldedit-bukkit-6.1.7-SNAPSHOT-dist.jar:?]
22.07 17:19:46 [Server] INFO at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[worldedit-bukkit-6.1.7-SNAPSHOT-dist.jar:?]
22.07 17:19:46 [Server] INFO at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:248) [worldedit-bukkit-6.1.7-SNAPSHOT-dist.jar:?]
22.07 17:19:46 [Server] INFO at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source) ~[?:?]
22.07 17:19:46 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
22.07 17:19:46 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
22.07 17:19:46 [Server] INFO at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) [worldedit-bukkit-6.1.7-SNAPSHOT-dist.jar:?]
22.07 17:19:46 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) [worldedit-bukkit-6.1.7-SNAPSHOT-dist.jar:?]
22.07 17:19:46 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [worldedit-bukkit-6.1.7-SNAPSHOT-dist.jar:?]
22.07 17:19:46 [Server] INFO at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [worldedit-bukkit-6.1.7-SNAPSHOT-dist.jar:?]
22.07 17:19:46 [Server] INFO at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:247) [worldedit-bukkit-6.1.7-SNAPSHOT-dist.jar:?]
22.07 17:19:46 [Server] INFO at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) [worldedit-bukkit-6.1.7-SNAPSHOT-dist.jar:?]
22.07 17:19:46 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-7228328-af1c013]
22.07 17:19:46 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot.jar:git-Spigot-7228328-af1c013]
22.07 17:19:46 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot.jar:git-Spigot-7228328-af1c013]
22.07 17:19:46 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot.jar:git-Spigot-7228328-af1c013]
22.07 17:19:46 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-7228328-af1c013]
22.07 17:19:46 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-7228328-af1c013]
22.07 17:19:46 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7228328-af1c013]
22.07 17:19:46 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
22.07 17:19:46 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
22.07 17:19:46 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-7228328-af1c013]
22.07 17:19:46 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-7228328-af1c013`

How can I fix this?

**Comment by mgflames** [comment]
As well as this question, is there a way to make it so that when you break blocks, they go into drops?

**Comment by LiamTownsley** [comment]
Are you running Spigot 1.11.2?

I am not sure about that one.

**Comment by mgflames** [comment]
@DUFC-Liam I am running Spigot 1.12.

**Comment by mayokek** [comment]
I believe TF-WorldEdit isn't available for Spigot 1.12. So, you have to manually compile 1.12 onto TF-WorldEdit.

**Comment by mgflames** [comment]
Does Spigot 1.11.2 allow 1.12 clients to join though?

**Comment by ItzLevvie** [comment]
@InfamousYT No, you would need ProtocolSupport for that

**Comment by aokod** [comment]
TF-WorldEdit is pretty much depreciated. It doesn't support anything close to new and you really shouldn't be using it on anything above _1.8.3_.

**Comment by aokod** [comment]
@InfamousYT @ItzLevvie ProtocolSupport doesn't provide support for client versions newer than that of the server. Use [ViaVersion](https://www.spigotmc.org/resources/viaversion.19254/) for that.

**Comment by Wild1145** [comment]
TF-WorldEdit should be working up to 1.11, the fact that you run a 1.11 Plugin on a 1.12 server would make little difference. ProticolSupport has nothing to do with WorldEdit at all.

**Comment by ItzLevvie** [comment]
**_ProtocolSupport doesn't provide support for client versions newer than that of the server. Use ViaVersion for that. - @ir1x_**

Actually, the ProtocolSupport I've linked is a nightly build which allows 1.11.2 clients and below to join a 1.12 server.

**Comment by Wild1145** [comment]
Guys, Proticol support has nothing to do with this issue, WorldEdit has no dependency on ProticolLib, and it is of no use here.

**Comment by ItzLevvie** [comment]
@InfamousYT to fix this issue you can compile from my [TF-WorldEdit](https://github.com/ItzLevvie/TF-WorldEdit)

**Comment by Wild1145** [comment]
Thanks for contributing. I am closing this issue for inactivity. Should you have anything further to add in the future please either re-open the issue yourself or tag a member of staff and we will re-open the issue for further discussion.
