### ISSUE TITLE
/cake broken in 1.12 prerelease

### ISSUE THREAD

**Issue by lemonsked** [TotalFreedom/TotalFreedomMod#2121]
When you do /cake, it says ingame: Command error: not supported in this minecraft version. 
This is due to the fact that achievements do not exist in versions of minecraft later then 1.12
Replaces with advancements.
Error in logs:

```:[14:45:20 ERROR]: [TotalFreedomMod] Uncaught exception executing command: cake
:[14:45:20 ERROR]: [TotalFreedomMod] nulljava.lang.UnsupportedOperationException: Not supported in this Minecraft version.
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.awardAchievement(CraftPlayer.java:593)
	at me.totalfreedom.totalfreedommod.command.Command_cake.run(Command_cake.java:47)
	at me.totalfreedom.totalfreedommod.command.FreedomCommand.runCommand(FreedomCommand.java:53)
	at me.totalfreedom.totalfreedommod.command.FreedomCommandExecutor.onCommand(FreedomCommandExecutor.java:81)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651)
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1386)
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1221)
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Wild1145** [comment]
Doing some research 1.12 removed Achievements and replaced them with Advancements. We should be able to swap the awarding of the Achievement out for an Advancement.

**Comment by lemonsked** [comment]
I already stated that in the OP, but thanks

**Comment by Wild1145** [comment]
@OxLemonxO Apologies, assumed it hadn't been with #2133 just commenting it out, evidently this was not read properly when the PR was raised.
