### ISSUE TITLE
Unable to use WorldEdit

### ISSUE THREAD

**Issue by ezAxeG** [TotalFreedom/TotalFreedomMod#2135]
Everytime i type //set 1 it says this

[InGame]
Missing value for <fillPattern>

[Console]
```
java.lang.NoSuchMethodError: com.google.common.base.Objects.firstNonNull(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        at com.sk89q.worldedit.function.factory.Apply.createFromContext(Apply.java:51) ~[TF-WorldEdit-6.1.1.jar:?]
        at com.sk89q.worldedit.function.factory.Apply.createFromContext(Apply.java:33) ~[TF-WorldEdit-6.1.1.jar:?]
        at com.sk89q.worldedit.command.composition.SelectionCommand.call(SelectionCommand.java:83) ~[TF-WorldEdit-6.1.1.jar:?]
        at com.sk89q.worldedit.command.composition.SelectionCommand.call(SelectionCommand.java:46) ~[TF-WorldEdit-6.1.1.jar:?]
        at com.sk89q.worldedit.util.command.composition.LegacyCommandAdapter.call(LegacyCommandAdapter.java:52) ~[TF-WorldEdit-6.1.1.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.call(SimpleDispatcher.java:125) ~[TF-WorldEdit-6.1.1.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:270) [TF-WorldEdit-6.1.1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) [TF-WorldEdit-6.1.1.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) [TF-WorldEdit-6.1.1.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [TF-WorldEdit-6.1.1.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [TF-WorldEdit-6.1.1.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:242) [TF-WorldEdit-6.1.1.jar:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) [TF-WorldEdit-6.1.1.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```
Anybody can help?

**Comment by ncurran02** [comment]
It's outdated.

**Comment by ItzLevvie** [comment]
@ezAxeG https://github.com/ItzLevvie/TF-WorldEdit

**Comment by ezAxeG** [comment]
@ItzLevvie 6.1? Or 1.12.2?

**Comment by ItzLevvie** [comment]
@ezAxeG It's TF-WorldEdit 6.1.9 for 1.12.2 & below servers

**Comment by aokod** [comment]
Just don't use TF-WorldEdit. There's little benefit to having it.

**Comment by Wild1145** [comment]
Need to know more info, what server version are you running, what branches / builds are you running of TFM and TF-WorldEdit?
