### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#549]
This happened immediately following a spambot attack from a single IP.

http://totalfreedom.boards.net/thread/22282/y5vaiylf

```
[15:59:23 ERROR]: [TotalFreedomMod] nulljava.util.ConcurrentModificationException

at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)

at java.util.HashMap$KeyIterator.next(HashMap.java:956)

at me.StevenLawson.TotalFreedomMod.TFM_UuidManager.save(TFM_UuidManager.java:72)

at me.StevenLawson.TotalFreedomMod.TFM_UuidManager.getUniqueId(TFM_UuidManager.java:136)

at me.StevenLawson.TotalFreedomMod.TFM_PlayerData.<init>(TFM_PlayerData.java:65)

at me.StevenLawson.TotalFreedomMod.TFM_PlayerData.getPlayerData(TFM_PlayerData.java:107)

at me.StevenLawson.TotalFreedomMod.Listener.TFM_PlayerListener.onPlayerChat(TFM_PlayerListener.java:547)

at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:606)

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298)

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509)

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:491)

at net.minecraft.server.v1_7_R4.PlayerConnection.chat(PlayerConnection.java:965)

at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:905)

at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28)

at net.minecraft.server.v1_7_R4.PacketPlayInChat$1.run(PacketPlayInChat.java:59)

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)

at java.util.concurrent.FutureTask.run(FutureTask.java:262)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

at java.lang.Thread.run(Thread.java:745)

```

**Comment by JeromSar** [comment]
@ChargedCreeper Thanks for the report. This bug has been fixed in the latest release of TFM, however. :)
