### ISSUE TITLE
/enchant NullPointerException

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#550]
[00:48:58 INFO]: [PREPROCESS_COMMAND] iPandaFTW(iPandaFTW): /enchant list
:[00:48:58 INFO]: [TotalFreedomMod] Command Error: enchant
:[00:48:58 ERROR]: [TotalFreedomMod] nulljava.lang.NullPointerException
	at net.minecraft.server.v1_7_R4.EnchantmentDurability.canEnchant(SourceFile:33)
	at org.bukkit.craftbukkit.v1_7_R4.enchantments.CraftEnchantment.canEnchantItem(CraftEnchantment.java:57)
	at me.StevenLawson.TotalFreedomMod.Commands.Command_enchant.run(Command_enchant.java:38)
	at me.StevenLawson.TotalFreedomMod.Commands.TFM_CommandHandler.handleCommand(TFM_CommandHandler.java:70)
	at me.StevenLawson.TotalFreedomMod.TotalFreedomMod.onCommand(TotalFreedomMod.java:208)
	at me.StevenLawson.TotalFreedomMod.Commands.TFM_CommandLoader$TFM_DynamicCommand.execute(TFM_CommandLoader.java:307)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767)
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043)
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880)
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28)
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65)
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186)
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by xDestroyer217** [comment]
I think due to 1.8, eh. maybe.

**Comment by JeromSar** [comment]
Definately a Spigot Bug. :/

**Comment by Wild1145** [comment]
@ChargedCreeper As its a spigot bug its probably worth creating a thread over at: http://www.spigotmc.org/forums/bugs-feature-requests.8/ so they can take a look at it ;)
