### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by AlexFreedomMod** [TotalFreedom/TotalFreedomMod#592]
When i was testing a custom version of totalfreedommod on a test server this happend.

LOG INFO:
Loading libraries, please wait...
[15:10:56 INFO]: Starting minecraft server version 1.8
[15:10:56 WARN]: To start the server with more ram, launch it as "java -Xmx1024M -Xms1024M -jar minecraft_server.jar"
[15:10:56 INFO]: Loading properties
[15:10:56 INFO]: Default game type: SURVIVAL
[15:10:56 INFO]: Generating keypair
[15:10:56 INFO]: Starting Minecraft server on *:40489
[15:10:57 INFO]: This server is running CraftBukkit version git-Bukkit-15e81cf (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[15:10:57 ERROR]: Could not load 'plugins/ZaramaFreedomMod.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/StevenLawson/TotalFreedomMod/TotalFreedomMod : Unsupported major.minor version 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:288) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.<init>(CraftServer.java:250) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at net.minecraft.server.v1_8_R1.PlayerList.<init>(PlayerList.java:69) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at net.minecraft.server.v1_8_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:133) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:473) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.UnsupportedClassVersionError: me/StevenLawson/TotalFreedomMod/TotalFreedomMod : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_79]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_79]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_79]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_79]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_79]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_79]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_79]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_79]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_79]
        at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        ... 9 more
[15:10:57 INFO]: [ClearLag] Loading ClearLag v2.7.7
[15:10:57 INFO]: [CoreProtect] Loading CoreProtect v2.10.0
[15:10:57 INFO]: [Essentials] Loading Essentials vTeamCity
[15:10:57 INFO]: [EssentialsSpawn] Loading EssentialsSpawn vTeamCity
[15:10:58 INFO]: Preparing level "world"
[15:10:58 INFO]: Preparing start region for level 0 (Seed: -7169648335500366528)
[15:10:59 INFO]: Preparing spawn area: 56%
[15:10:59 INFO]: Preparing start region for level 1 (Seed: -7169648335500366528)
[15:11:00 INFO]: Preparing start region for level 2 (Seed: -7169648335500366528)
[15:11:00 INFO]: [ClearLag] Enabling ClearLag v2.7.7
[15:11:00 INFO]: [ClearLag] Loading modules...
[15:11:00 WARN]: [ClearLag] mob-range requires you to use bukkit v1.7_r4 (1.7.10)
[15:11:00 INFO]: [ClearLag] Modules have been loaded!
[15:11:00 INFO]: [ClearLag] Clearlag is now enabled!
[15:11:00 INFO]: [CoreProtect] Enabling CoreProtect v2.10.0
[15:11:00 INFO]: [ClearLag] Checking for updates...
[15:11:01 INFO]: CoreProtect version 2.10.0 is enabled!
[15:11:01 INFO]: [CoreProtect] Using SQLite for data storage.
[15:11:01 INFO]: [Essentials] Enabling Essentials vTeamCity
[15:11:01 INFO]: Bukkit version format changed. Version not checked.
[15:11:01 INFO]: git-Bukkit-15e81cf (MC: 1.8)
[15:11:01 INFO]: 1.8-R0.1-SNAPSHOT
[15:11:01 INFO]: [Essentials] Starting Essentials ban format conversion
[15:11:01 INFO]: Using locale en_GB
[15:11:01 INFO]: Using locale en_GB
[15:11:01 INFO]: [ClearLag] No updates found!
[15:11:02 INFO]: Essentials: Using config file enhanced permissions.
[15:11:02 INFO]: Permissions listed in as player-commands will be given to all users.
[15:11:02 INFO]: [EssentialsSpawn] Enabling EssentialsSpawn vTeamCity
[15:11:02 INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:11:02 INFO]: Done (4.260s)! For help, type "help" or "?"
[15:11:02 INFO]: Starting GS4 status listener
[15:11:02 INFO]: Query running on 0.0.0.0:40489
[15:11:42 INFO]: I used /rl.
[15:11:42 INFO]: CONSOLE: Please note that this command is not supported and may cause issues when using some plugins.
[15:11:42 INFO]: CONSOLE: If you encounter any issues please use the /stop command to restart your server.
[15:11:42 INFO]: [EssentialsSpawn] Disabling EssentialsSpawn vTeamCity
[15:11:42 INFO]: [Essentials] Disabling Essentials vTeamCity
[15:11:42 INFO]: [CoreProtect] Disabling CoreProtect v2.10.0
[15:11:43 INFO]: [CoreProtect] Finishing up data logging. Please wait...
[15:11:43 INFO]: [CoreProtect] Success! Resuming server shutdown.
[15:11:43 INFO]: [ClearLag] Disabling ClearLag v2.7.7
[15:11:43 ERROR]: Could not load 'plugins/IslandFreedomMod.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/StevenLawson/TotalFreedomMod/TotalFreedomMod : Unsupported major.minor version 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:288) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:723) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.Bukkit.reload(Bukkit.java:543) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:625) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:611) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:320) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:285) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.UnsupportedClassVersionError: me/StevenLawson/TotalFreedomMod/TotalFreedomMod : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_79]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_79]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_79]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_79]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_79]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_79]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_79]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_79]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_79]
        at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        ... 14 more
[15:11:43 INFO]: [ClearLag] Loading ClearLag v2.7.7
[15:11:43 INFO]: [CoreProtect] Loading CoreProtect v2.10.0
[15:11:43 INFO]: [Essentials] Loading Essentials vTeamCity
[15:11:43 INFO]: [EssentialsSpawn] Loading EssentialsSpawn vTeamCity
[15:11:43 INFO]: [ClearLag] Enabling ClearLag v2.7.7
[15:11:43 INFO]: [ClearLag] Loading modules...
[15:11:43 WARN]: [ClearLag] mob-range requires you to use bukkit v1.7_r4 (1.7.10)
[15:11:43 INFO]: [ClearLag] Modules have been loaded!
[15:11:43 INFO]: [ClearLag] Clearlag is now enabled!
[15:11:43 INFO]: [CoreProtect] Enabling CoreProtect v2.10.0
[15:11:43 INFO]: [ClearLag] Checking for updates...
[15:11:43 INFO]: CoreProtect version 2.10.0 is enabled!
[15:11:43 INFO]: [CoreProtect] Using SQLite for data storage.
[15:11:43 INFO]: [Essentials] Enabling Essentials vTeamCity
[15:11:43 INFO]: Bukkit version format changed. Version not checked.
[15:11:43 INFO]: git-Bukkit-15e81cf (MC: 1.8)
[15:11:43 INFO]: 1.8-R0.1-SNAPSHOT
[15:11:43 INFO]: [Essentials] Starting Essentials ban format conversion
[15:11:43 INFO]: Using locale en_GB
[15:11:43 INFO]: [ClearLag] No updates found!
[15:11:44 INFO]: Using locale en_GB
[15:11:44 INFO]: Essentials: Using config file enhanced permissions.
[15:11:44 INFO]: Permissions listed in as player-commands will be given to all users.
[15:11:44 INFO]: [EssentialsSpawn] Enabling EssentialsSpawn vTeamCity
[15:11:44 INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:11:44 INFO]: CONSOLE: Reload complete.
pl
[15:11:45 INFO]: Plugins (4): ClearLag, CoreProtect, Essentials, EssentialsSpawn

**Comment by AlexFreedomMod** [comment]
I just found out there was an error in the TFM_Playerrank.

**Comment by JeromSar** [comment]
This happens when you compile TFM with a higher JDK version than the JRE version you run it with. Verify your java version and recompile to fix. :)

**Comment by AlexFreedomMod** [comment]
@JeromSar, What version do i compile it with then.

**Comment by JeromSar** [comment]
Any version above 1.6 will work, although if you open TFM in Netbeans (which you should definitely do!), JDK 1.7 should be default for you. As long as the JRE version is higher than the JRE version, all java applications will run fine.

**Comment by AlexFreedomMod** [comment]
JRE Version is higher then the JRE version?

**Comment by AlexFreedomMod** [comment]
Also, it was working on another server, but the plugin didn't work too well because well it wasn't running the right version of spigot 1.8 for TFM to work.

**Comment by JeromSar** [comment]
@AlexFreedomMod sorry, corrected my comment

**Comment by AlexFreedomMod** [comment]
ok.

**Comment by AlexFreedomMod** [comment]
Let me get JRE 8.

**Comment by AlexFreedomMod** [comment]
@JeromSar  I got netbeans but now issue #600 is happening I'm using netbeans ide 8.0.2 EE.

**Comment by DaBoyTM** [comment]
@JeromSar 
The JDK and JRE are suppose to be same,
@AlexFreedomMod 
Use JDK 1.8.0 and JRE 1.8.0

**Comment by AlexFreedomMod** [comment]
Netbeans error (Did you see the pictures)

I'm going to try to get jre 1.8.2
