### ISSUE TITLE
TFM does not work on my server

### ISSUE THREAD

**Issue by DaBoyTM** [TotalFreedom/TotalFreedomMod#593]
CONSOLE ERRORS:
[06:12:48 ERROR]: Error occurred while enabling DragonRealmsMod v4.4 (Is it up to date?)
java.lang.NullPointerException
        at me.StevenLawson.TotalFreedomMod.TFM_Announcer.load(TFM_Announcer.java:48) ~[?:?]
        at me.StevenLawson.TotalFreedomMod.TotalFreedomMod.onEnable(TotalFreedomMod.java:104) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:341) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:473) [craftbukkit-1.8.jar:git-Bukkit-15e81cf]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]

It does display on /pl but does not work

**Comment by DaBoyTM** [comment]
Nvm, it is working now.
