### ISSUE TITLE
Unable to Freeze

### ISSUE THREAD

**Issue by xDestroyer217** [TotalFreedom/TotalFreedomMod#608]
:[21:37:44 ERROR]: [TotalFreedomMod] Command Error: fr
:[21:37:44 ERROR]: [TotalFreedomMod] nulljava.lang.IllegalArgumentException: Cannot make player fly if getAllowFlight() is false
        at org.bukkit.craftbukkit.v1_8_R2.entity.CraftPlayer.setFlying(CraftPlayer.java:1150)
        at me.StevenLawson.TotalFreedomMod.TFM_PlayerData.setFrozen(TFM_PlayerData.java:230)
        at me.StevenLawson.TotalFreedomMod.Commands.Command_fr.setAllFrozen(Command_fr.java:80)
        at me.StevenLawson.TotalFreedomMod.Commands.Command_fr.run(Command_fr.java:29)
        at me.StevenLawson.TotalFreedomMod.Commands.TFM_CommandHandler.handleCommand(TFM_CommandHandler.java:70)
        at me.StevenLawson.TotalFreedomMod.TotalFreedomMod.onCommand(TotalFreedomMod.java:217)
        at me.StevenLawson.TotalFreedomMod.Commands.TFM_CommandLoader$TFM_DynamicCommand.execute(TFM_CommandLoader.java:307)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
        at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139)
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974)
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712)
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
        at java.lang.Thread.run(Thread.java:745)

:[21:37:45 INFO]: ImALuckyGuy issued server command: /say No, you're not an admin.

**Comment by AlexFreedomMod** [comment]
They need to be flying to freeze them.

**Comment by AlexFreedomMod** [comment]
You made 8 issues already :large_blue_circle:

**Comment by Wild1145** [comment]
>:[21:37:44 ERROR]: [TotalFreedomMod] nulljava.lang.IllegalArgumentException: Cannot make player fly if getAllowFlight() is false

There in lies your problem, you're trying to get someone to fly, and you havent given them permissions to fly.

**Comment by AlexFreedomMod** [comment]
@Wild1145 thats what i said earlyer

AlexFreedomMod commented an hour ago
They need to be flying to freeze them.
