### ISSUE TITLE
/saconfig clearme broken

### ISSUE THREAD

**Issue by OxLemonxO** [TotalFreedom/TotalFreedomMod#629]
[15:56:48] [Server thread/INFO]: [PLAYER_COMMAND] OxLemonxO ( OxLemonxO): /saconfig clearme
[15:56:48] [Server thread/INFO]: OxLemonxO - Cleaning my supered IPs
[15:56:48] [Server thread/ERROR]: [TotalFreedomMod] Command Error: saconfig
[15:56:48] [Server thread/ERROR]: [TotalFreedomMod] null
java.lang.NullPointerException
at me.StevenLawson.TotalFreedomMod.Commands.Command_saconfig.run(Command_saconfig.java:66) ~[TotalFreedomMod.jar:?]
at me.StevenLawson.TotalFreedomMod.Commands.TFM_CommandHandler.handleCommand(TFM_CommandHandler.java:70) [TotalFreedomMod.jar:?]
at me.StevenLawson.TotalFreedomMod.TotalFreedomMod.onCommand(TotalFreedomMod.java:217) [TotalFreedomMod.jar:?]
at me.StevenLawson.TotalFreedomMod.Commands.TFM_CommandLoader$TFM_DynamicCommand.execute(TFM_CommandLoader.java:307) [TotalFreedomMod.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_71]
at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_71]
at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]

Here's the error.

**Comment by Wild1145** [comment]
You got a pesky NullPointer Exception here:

    int counter = admin.getIps().size() - 1;

My guess is that you had 1 IP and its done 1 - 1 = 0. Counter is now 0 throwing a NPE.

**Comment by WickedGamingUK** [comment]
@Wild1145 Sounds logical, just needs to check if the amount of IPs the admin has is 0 just to do nothing and say that nothing needs to be done as there's only one IP for the admin.

**Comment by JeromSar** [comment]
@Wild1145 @WickedGamingUK  That's not how NullPointerExceptions work.

**Comment by WickedGamingUK** [comment]
@JeromSar Oh yeah, ignore me.

**Comment by Wild1145** [comment]
@JeromSar Oh yeah... Whoops, having a slow day...
