### ISSUE TITLE
Command error

### ISSUE THREAD

**Issue by AlexFreedomMod** [TotalFreedom/TotalFreedomMod#694]
:36:21 INFO]: [PLAYER_COMMAND] RedTheDragon_ (RedTheDragon_): /afm 
:[20:36:21 ERROR]: [AlexFreedomMod] Command Error: afm
:[20:36:21 ERROR]: [AlexFreedomMod] nulljava.lang.ArrayIndexOutOfBoundsException: 0
	at me.StevenLawson.TotalFreedomMod.Commands.Command_afm.run(Command_afm.java:35)
	at me.StevenLawson.TotalFreedomMod.Commands.TFM_CommandHandler.handleCommand(TFM_CommandHandler.java:70)
	at me.StevenLawson.TotalFreedomMod.TotalFreedomMod.onCommand(TotalFreedomMod.java:227)
	at me.StevenLawson.TotalFreedomMod.Commands.TFM_CommandLoader$TFM_DynamicCommand.execute(TFM_CommandLoader.java:307)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139)
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974)
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712)
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
	at java.lang.Thread.run(Thread.java:745)

**Comment by JeromSar** [comment]
This is not a TFM command.
